### ISSUE TITLE
On Simple and on Shiny add Horizontal pale background on odd rows on View Grid

### ISSUE THREAD

**Issue by morena** [geeksoflondon/grid4rails#14]
Experiment a bit, let's see what works best. 
We think it's more difficult to follow through horizontally more than vertically.

This change should be also inherited on the Now view (separate issue to just make sure i happens)

**Comment by morena** [comment]
To do so we need a counter of some sort so we can tell if the row is odd or even. I don't know how to add this in the backend and where, can anybody add a .odd class to the th.room and the td on that row and let me know so  can then style it please?

**Comment by markstickley** [comment]
I've pushed a fix for this issue. I chose a diplomatic light grey background for the zebra strips, but I'm no designer so feel free to change. I chose to highlight the even rows instead of the odd as having the highlight adjacent to the underline for the time slot looked odd.

I flexed my ruby muscles for the first time in the back end - pleased it worked! I don't know if there's a coding style or convention either in Ruby or this particular project so feel free to correct me.

I monkeyed around a bit with the CSS, removing the borders and instead using padding to space the cells. I hope this is OK, but the form's border-collapse was making giving the rows a background colour very tricky and turning off border-collapse had it's own issues.

**Comment by morena** [comment]
Thanks for the odd even Mark! And for the borders! They had to go if we wanted a solid horizontal stripe!
 I can't see the background colour, is it just me?

**Comment by morena** [comment]
I can see the bg now it is a bit to subtle, but it might just be my screen so let me know if you want me to make it a bit darker :)

**Comment by markstickley** [comment]
I dunno, it looks OK on my screen but colours on Macs are known to be a bit different...
