### ISSUE TITLE
Schedule Talk - emphasise empty slots

### ISSUE THREAD

**Issue by morena** [geeksoflondon/grid4rails#26]
Should we tone up the empty slots or tone down the full ones?

Experiment...

**Comment by markstickley** [comment]
I don't think we should tone down the full ones. It might make them look as if they already happened or something.

Perhaps there should be some kind of status symbol? Another type of status that could be useful would be to mark breaks and other camp-level slots so that they stand out. How is best to do this I don't know and is quite a design-orientated decision, something I'm not sure I should be making? But if no-one minds I don't mind giving it a bash.
