### ISSUE TITLE
Validate Markup

### ISSUE THREAD

**Issue by martian-a** [geeksoflondon/grid4rails#83]
Small and medium are both using XHTML 1.0 Transitional; Large is using HTML 5.  Small and medium are healthy.  Large is in trouble because, apparently, elements traditionally referred to as block level elements are no longer valid content for a table cell.  I say that's madness and we either change the doctype or live with it.

**Comment by leeky** [comment]
Out of interest where are you reading about certain elements no longer being valid within table cells? Because the HTML5 standard is very much in draft form and lets you do all sorts of crazy stuff legitimately, I'd have thought we'd be ok.

I generally use the [HTML5 Lint tool](http://lint.brihten.com/html/) to validate my code and that's about it.

**Comment by martian-a** [comment]
W3C validator and current draft of spec.

**Comment by martian-a** [comment]
Used W3C validator.
